version: '3.8'

services:
  am5_dev: # grass + r + app
    image: fredmoser/accessmod:5.7.15-alpha
    privileged: true
    ports:
      - '3030:3030'
      - '3434:3434'
      - '3939:3939'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - am5_dev_tmp:/tmp
      - am5_dev_data:/data/dbgrass
      - am5_dev_cache:/data/cache
      - am5_dev_logs:/data/logs
     # - type: bind
     #  source: ./_dbgrass 
     #  target: /data/dbgrass
      - type: bind
        source: .
        target: /appdev

volumes:
  am5_dev_tmp:
  am5_dev_data:
  am5_dev_cache:
  am5_dev_logs:


