version: '3.2'
services:
  am5: # common + grass + r + app
    build: am5_app/.
    image: fredmoser/am5_app:5.6.51
    ports:
     - "3030:3030"
     - "3434:3434"
     - "3939:3939"
    volumes:
      - type: bind
        source: ../.
        target: /app
      - type: bind
        source: ../_dbgrass
        target: /data/dbgrass
