name: build_qemu

on:
  push:
    branches:
      - staging
  workflow_dispatch:
    inputs:
      version:
        description: "VM Version"
        required: false
        default: "5.9"
        type: string

jobs:
  build-x86:
    name: Build x86_64 VM
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils
          sudo modprobe nbd max_part=16

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          branch: v3.21

      - name: Build VM Image
        run: |
          cd qemu
          apk add --no-cache alpine-make-vm-image qemu-img docker bash
          # Set default version if input is empty
          VERSION="${{ github.event.inputs.version }}"
          if [ -z "$VERSION" ]; then
            VERSION="5.9"
          fi
          # Update version in config.sh using more robust pattern matching
          sed -i "s/^export VM_VERSION=.*$/export VM_VERSION=\"${VERSION}\"/" config.sh
          ./build.sh x86_64
        shell: alpine.sh --root {0}

      - name: Upload x86_64 Image
        uses: actions/upload-artifact@v4
        with:
          name: accessmod-vm-${{ github.event.inputs.version || '5.9' }}_x86_64
          path: _build/vm/alpine-accessmod-${{ github.event.inputs.version || '5.9' }}.vdi
