name: build_qemu

on:
  push:
    branches:
      - staging
  workflow_dispatch:
    inputs:
      version:
        description: "VM Version"
        required: false
        default: "5.9"
        type: string

jobs:
  build-x86:
    name: Build x86_64 VM
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils
          sudo modprobe nbd max_part=16

      - name: Checkout
        uses: actions/checkout@v4
      - name: Pre-pull Docker image and save archive
        run: |
          cd qemu
          # Determine VM version (fallback to default)
          VERSION="${{ github.event.inputs.version }}"
          if [ -z "$VERSION" ]; then
            VERSION="5.9"
          fi
          # Source config to get repository settings
          . ./config.sh
          # Pull the accessmod image and extract version
          docker pull "${AM5_REPO}:${AM5_VERSION_LATEST}"
          AM5_VERSION=$(docker run --rm --entrypoint="" "${AM5_REPO}:${AM5_VERSION_LATEST}" cat version.txt | tr -d '\r\n')
          # Ensure fs skeleton directory exists and save image archive
          mkdir -p fs/home/accessmod
          docker save "${AM5_REPO}:${AM5_VERSION}" -o fs/home/accessmod/docker_image.tar
          # Export variables for the build step
          echo "AM5_VERSION=$AM5_VERSION" >> $GITHUB_ENV
          echo "BUILD_VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Set up Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          branch: v3.21

      - name: Build VM Image
        run: |
          cd qemu
          apk add --no-cache alpine-make-vm-image qemu-img docker bash tar util-linux
          # Set default version if input is empty
          VERSION="${{ github.event.inputs.version }}"
          if [ -z "$VERSION" ]; then
            VERSION="5.9"
          fi
          # Build VM and perform OVA conversion within build.sh
          ./build.sh x86_64 "${VERSION}"
        shell: alpine.sh --root {0}

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: accessmod-vm-${{ github.event.inputs.version || '5.9' }}_x86_64
          path: qemu/_build
          if-no-files-found: warn
