name: ci

on:
  push:
    branches:
      - ci

env:
  DOCKER_REPO: 'fredmoser'
  DOCKER_NAME: 'accessmod'
  PACKER_VERSION: '1.10.1'
 
jobs:
  #  docker:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout
  #        uses: actions/checkout@v4
  #
  #      - name: Set up QEMU
  #        uses: docker/setup-qemu-action@v3
  #
  #      - name: Set up Docker Buildx
  #        uses: docker/setup-buildx-action@v3
  #
  #      - name: Login to Docker Hub
  #        uses: docker/login-action@v3
  #        with:
  #          username: ${{ secrets.DOCKERHUB_USERNAME }}
  #          password: ${{ secrets.DOCKERHUB_TOKEN }}
  #
  #      - name: Get version
  #        id: get_version
  #        run: echo "AM_VERSION=$(cat version.txt)" >> $GITHUB_ENV
  #
  #      - name: Build and push
  #        uses: docker/build-push-action@v5
  #        with:
  #          context: .
  #          file: ./docker/Dockerfile
  #          platforms: linux/amd64,linux/arm64
  #          push: true
  #          tags: ${{ env.DOCKER_REPO }}/${{ env.DOCKER_NAME }}:${{ env.AM_VERSION }}
  packer:
    runs-on: macos-14-large
    name: Run Packer on macOS
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install VirtualBox
        run: |
          brew install --cask virtualbox

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: Initialize Packer Configuration
        working-directory: ./packer
        run: packer init alpine.pkr.hcl

      - name: Validate Packer Template
        working-directory: ./packer
        run: packer validate alpine.pkr.hcl

      - name: Build with Packer
        working-directory: ./packer
        run: packer build -debug -force alpine.pkr.hcl

      - name: Upload OVA
        uses: actions/upload-artifact@v3
        with:
          name: packer-image
          path: packer/_build/*.ova
