name: build_qemu

on:
  push:
    branches:
      - staging
  workflow_dispatch:
    inputs:
      version:
        description: "VM Version"
        required: false
        default: "5.9"
        type: string

jobs:
  build-x86:
    name: Build x86_64 VM
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils
          sudo modprobe nbd max_part=16

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          branch: v3.21

      - name: Build VM Image
        run: |
          cd qemu
          apk add --no-cache alpine-make-vm-image qemu-img docker bash
          if [ -n "${{ github.event.inputs.version }}" ]; then
            sed -i "s/VM_VERSION=\"5.9\"/VM_VERSION=\"${{ github.event.inputs.version }}\"/" config.sh
          fi
          ./build.sh x86_64
        shell: alpine.sh --root {0}

      - name: Upload x86_64 Image
        uses: actions/upload-artifact@v4
        with:
          name: accessmod-vm-${{ github.event.inputs.version }}"_x86_64
          path: _build/vm/alpine-accessmod-5.9.vdi
