name: build_docker

on:
  push:
    branches:
      - main 
      - staging

env:
  DOCKER_REPO: "fredmoser"
  DOCKER_NAME: "accessmod"
  DOCKER_TAG_TEST: "test"
  DOCKER_TAG_LATEST: "latest"

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Test and build docker images
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version
        id: get_version
        run: echo "AM_VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Build test version
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          load: true
          tags: ${{ env.DOCKER_REPO }}/${{ env.DOCKER_NAME }}:${{ env.DOCKER_TAG_TEST }}

      - name: Run tests
        env:
          DOCKER_TAG: "${{ env.DOCKER_TAG_TEST }}"
        run: ./test.sh

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}/${{ env.DOCKER_NAME }}:${{ env.AM_VERSION }}
            ${{ env.DOCKER_REPO }}/${{ env.DOCKER_NAME }}:${{ env.DOCKER_TAG_LATEST }}

