name: Build and Release Electron App

on:
  push:
    branches:
      - update/electron_dependencies
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: macos-latest
            target: dmg
          - os: windows-latest
            target: nsis
          - os: ubuntu-latest
            target: AppImage
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Update Image
        working-directory: ./electron
        run: ./update_image.sh
        shell: bash

      - name: Install Dependencies
        run: yarn install

      - name: Build Electron App
        uses: samuelmeuli/action-electron-builder@v1
        with:
          electron_version: 29.1.5 
          package_root: ./electron/
          build_command: yarn run dist
          args: --${{ matrix.target }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-build
          path: dist/*
