name: Update Electron app

on:
  push:
    branches:
      - update/electron_dependencies
  pull_request:

jobs:

  update_image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: ubutu-latest
            arch: amd64
          - os: macos-14
            arch: arm64
    steps:
      - uses: actions/checkout@v4
      - name: Use docker
        uses: actions-hub/docker/cli@master
        env:
          SKIP_LOGIN: true
      - name: Update image
        working-directory: ./electron
        run: ./update_image.sh
        shell: bash
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: accessmod-docker-archive-${{ matrix.arch }}
          path: ./electron/app/docker/accessmod-docker.tar.gz

  build:
    runs-on: ${{ matrix.os }}
    needs: update_image
    strategy:
      matrix:
        include:
          - os: macos-14
            platform: mac
            arch: arm64
          - os: macos-12
            platform: mac
            arch: amd64
          - os: windows-2022
            platform: win
            arch: amd64
          - os: ubuntu-22.04
            platform: linux
            arch: amd64
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: accessmod-docker-archive-${{ matrix.arch }}
          path: ./electron/app/docker/

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install Dependencies
        working-directory: ./electron 
        run: yarn install

      - name : Build
        working-directory: ./electron 
        env :
          GH_TOKEN: ${{ secrets.github_token }}
        run : yarn electron-builder --${{ matrix.platform }} --${{ matrix.arch }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: accessmod-desktop-${{ matrix.platform }}-${{ matrix.arch }}
          path: ./electron/dist/*
