name: Update Electron app

on:
  push:
    branches:
      - update/electron_dependencies
  pull_request:

jobs:

  update_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use docker 
        uses: actions-hub/docker/cli@master
        env:
          SKIP_LOGIN: true
      - name: Update image
        working-directory: ./electron
        run: ./update_image.sh
        shell: bash
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: accessmod_docker_archive
          path: ./electron/app/docker/accessmod-docker.tar.gz

  build:
    runs-on: ${{ matrix.os }}
    needs: update_image
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: macos-latest
            target: dmg
          - os: windows-latest
            target: nsis
          - os: ubuntu-latest
            target: AppImage
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: accessmod_docker_archive
          path: ./electron/app/docker/

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: yarn install

      - name: Build Electron App
        uses: samuelmeuli/action-electron-builder@v1
        with:
          electron_version: 29.1.5
          package_root: ./electron/
          build_command: yarn run dist
          args: --${{ matrix.target }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-build
          path: dist/*
